services:
  earnlab_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: earnlab_db
    ports:
      - "5446:5432"
    volumes:
      - earnlab_db_data:/var/lib/postgresql/data

  earnlab_redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  earnlab_db_data: